# Generated by Django 6.1 on 2026-09-24 05:36

import core.imagenes
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tiendas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('habilitado', models.BooleanField(db_index=True, default=True)),
                ('fecha_baja', models.DateTimeField(blank=True, null=True)),
                ('nombre', models.CharField(max_length=80)),
                ('tienda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categorias', to='tiendas.tienda')),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('habilitado', models.BooleanField(db_index=True, default=True)),
                ('fecha_baja', models.DateTimeField(blank=True, null=True)),
                ('nombre', models.CharField(max_length=120)),
                ('descripcion', models.TextField(blank=True)),
                ('precio', models.PositiveIntegerField(help_text='En pesos chilenos.')),
                ('stock', models.PositiveIntegerField(default=0)),
                ('imagen', models.ImageField(blank=True, upload_to='productos/', validators=[core.imagenes.validar_tamano])),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='productos', to='catalogo.categoria')),
                ('tienda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos', to='tiendas.tienda')),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.AddConstraint(
            model_name='categoria',
            constraint=models.UniqueConstraint(fields=('tienda', 'nombre'), name='categoria_unica_por_tienda'),
        ),
    ]
