# Generated by Django 6.1 on 2026-09-24 05:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tiendas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Metrica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metodo', models.CharField(max_length=10)),
                ('ruta', models.CharField(max_length=255)),
                ('status', models.PositiveSmallIntegerField()),
                ('duracion_ms', models.PositiveIntegerField()),
                ('fecha', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('tienda', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='metricas', to='tiendas.tienda')),
            ],
        ),
    ]
