# Generated by Django 6.1 on 2026-09-24 05:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogo', '0001_initial'),
        ('tiendas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoCarrito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('nombre', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='EstadoPedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('nombre', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Carrito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('habilitado', models.BooleanField(db_index=True, default=True)),
                ('fecha_baja', models.DateTimeField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carritos', to='tiendas.perfilusuario')),
                ('tienda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carritos', to='tiendas.tienda')),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ventas.estadocarrito')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('habilitado', models.BooleanField(db_index=True, default=True)),
                ('fecha_baja', models.DateTimeField(blank=True, null=True)),
                ('total', models.PositiveIntegerField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedidos', to='tiendas.perfilusuario')),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ventas.estadopedido')),
                ('tienda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedidos', to='tiendas.tienda')),
            ],
            options={
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='ItemPedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('habilitado', models.BooleanField(db_index=True, default=True)),
                ('fecha_baja', models.DateTimeField(blank=True, null=True)),
                ('cantidad', models.PositiveIntegerField()),
                ('precio_unitario', models.PositiveIntegerField()),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items_pedido', to='catalogo.producto')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='ventas.pedido')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ItemCarrito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('habilitado', models.BooleanField(db_index=True, default=True)),
                ('fecha_baja', models.DateTimeField(blank=True, null=True)),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('carrito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='ventas.carrito')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items_carrito', to='catalogo.producto')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('carrito', 'producto'), name='un_item_por_producto_y_carrito')],
            },
        ),
    ]
