# Generated by Django 6.1 on 2026-09-24 05:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0002_alter_producto_categoria'),
        ('ventas', '0002_datos_iniciales'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemcarrito',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='items_carrito', to='catalogo.producto'),
        ),
        migrations.AlterField(
            model_name='itempedido',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='items_pedido', to='catalogo.producto'),
        ),
    ]
