# Generated by Django 6.1 on 2026-09-24 05:36

import core.imagenes
import django.core.validators
import django.db.models.deletion
import tiendas.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60, unique=True)),
                ('precio_mensual', models.PositiveIntegerField(help_text='En pesos chilenos.')),
                ('max_productos', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=30, unique=True)),
                ('nombre', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Tienda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('habilitado', models.BooleanField(db_index=True, default=True)),
                ('fecha_baja', models.DateTimeField(blank=True, null=True)),
                ('nombre', models.CharField(max_length=100)),
                ('slug', models.CharField(max_length=30, unique=True, validators=[django.core.validators.RegexValidator('^[a-z0-9]([a-z0-9-]{0,28}[a-z0-9])?$', 'Solo minúsculas, números y guiones (sin espacios ni guion bajo).'), tiendas.models.validar_subdominio_libre], verbose_name='subdominio')),
                ('dominio_propio', models.CharField(blank=True, max_length=253, null=True, unique=True)),
                ('color_primario', models.CharField(default='#1B4332', max_length=7, validators=[django.core.validators.RegexValidator('^#[0-9A-Fa-f]{6}$', 'Usa un color hexadecimal, por ejemplo #1B4332.')])),
                ('logo', models.ImageField(blank=True, upload_to='logos/', validators=[core.imagenes.validar_tamano])),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tiendas', to='tiendas.plan')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PerfilUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('habilitado', models.BooleanField(db_index=True, default=True)),
                ('fecha_baja', models.DateTimeField(blank=True, null=True)),
                ('nombres', models.CharField(max_length=100)),
                ('apellido_paterno', models.CharField(max_length=60)),
                ('apellido_materno', models.CharField(blank=True, max_length=60)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL)),
                ('rol', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='perfiles', to='tiendas.rol')),
                ('tienda', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='perfiles', to='tiendas.tienda')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
