"""
Django settings for tienda_project project.

Generated by 'django-admin startproject' using Django 6.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.1/ref/settings/
"""

import os
from datetime import timedelta
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


def _load_env_file(path):
    """Carga variables de entorno desde un archivo .env simple (KEY=VALOR
    por línea). No se agrega python-dotenv como dependencia extra solo para
    esto; el archivo .env es local y nunca se sube a GitHub (ver .gitignore).
    """
    if not path.exists():
        return
    for line in path.read_text().splitlines():
        line = line.strip()
        if not line or line.startswith('#') or '=' not in line:
            continue
        key, value = line.split('=', 1)
        os.environ.setdefault(key.strip(), value.strip())


_load_env_file(BASE_DIR / '.env')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# Se lee desde .env (nunca queda fijo en el código, a diferencia de la prueba 1).
SECRET_KEY = os.environ.get('SECRET_KEY', 'django-insecure-solo-para-desarrollo-local')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DEBUG', 'False') == 'True'

# '.localhost' habilita cualquier subdominio (ej. zapatilleate.localhost:8000),
# necesario porque el multi-tenant se resuelve por subdominio.
ALLOWED_HOSTS = ['localhost', '127.0.0.1', '.localhost']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # Librerías de terceros
    'rest_framework',
    'rest_framework_simplejwt',
    'rest_framework_simplejwt.token_blacklist',
    'django_filters',
    'drf_spectacular',
    # Apps propias, separadas por dominio
    'core',
    'tiendas',
    'catalogo',
    'ventas',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    # Mide cuánto demora cada request (dashboard de tiempos de respuesta).
    'core.middleware.MetricasMiddleware',
    # Resuelve la tienda (tenant) según el subdominio: deja request.tienda.
    'core.middleware.TenantMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    # Lee el JWT de la cookie y deja request.user / request.perfil.
    'core.middleware.JWTAuthMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'tienda_project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'core.context_processors.global_ctx',
            ],
        },
    },
]

WSGI_APPLICATION = 'tienda_project.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': os.environ.get('DB_NAME', 'tienda_multitenant'),
        'USER': os.environ.get('DB_USER', 'tienda_app'),
        'PASSWORD': os.environ.get('DB_PASSWORD', ''),
        'HOST': os.environ.get('DB_HOST', '127.0.0.1'),
        'PORT': os.environ.get('DB_PORT', '3306'),
        'OPTIONS': {
            'charset': 'utf8mb4',
        },
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.1/topics/i18n/

LANGUAGE_CODE = 'es-cl'

TIME_ZONE = 'America/Santiago'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.1/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [BASE_DIR / 'static']

# Imágenes subidas (logos de tiendas y fotos de productos).
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# --- Multi-tenant -----------------------------------------------------------
# Dominio base de la plataforma. Cada tienda vive en <slug>.<DOMINIO_BASE>
# (ej. raiz.localhost:8000). Los navegadores resuelven *.localhost a 127.0.0.1
# solos, así que en desarrollo no hace falta tocar /etc/hosts.
DOMINIO_BASE = os.environ.get('DOMINIO_BASE', 'localhost')
# Hosts que NO son una tienda: son la plataforma (admin general, portada).
HOSTS_PLATAFORMA = [DOMINIO_BASE, '127.0.0.1', 'testserver']
PLATAFORMA_NOMBRE = 'Plataforma de Tiendas'
# Slug de la tienda de demostración (sandbox) que se puede reiniciar.
TIENDA_DEMO_SLUG = 'demo'

# Vista que se muestra si falla la verificación CSRF (en vez de la fea por defecto).
CSRF_FAILURE_VIEW = 'core.views.error_csrf'


# Email
# https://docs.djangoproject.com/en/6.1/topics/email/#topic-email-configuration

MAILERS = {
    'default': {
        'BACKEND': 'django.core.mail.backends.console.EmailBackend',
    },
}


# Django REST Framework
# https://www.django-rest-framework.org/api-guide/settings/

REST_FRAMEWORK = {
    # Autenticación propia (ver tienda_project/authentication.py): lee el
    # JWT desde una cookie HttpOnly en vez del header Authorization, para
    # que un XSS no pueda robar el token con JavaScript.
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'tienda_project.authentication.CookieJWTAuthentication',
    ),
    # Por defecto todo queda protegido; los endpoints públicos (ej. listar
    # productos de una tienda) se marcan explícitamente con AllowAny.
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
    'DEFAULT_FILTER_BACKENDS': (
        'django_filters.rest_framework.DjangoFilterBackend',
    ),
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
    'EXCEPTION_HANDLER': 'core.api.manejador_de_errores',
    'DEFAULT_RENDERER_CLASSES': ('rest_framework.renderers.JSONRenderer',),
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 20,
}


# djangorestframework-simplejwt
# https://django-rest-framework-simplejwt.readthedocs.io/

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=30),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
    'UPDATE_LAST_LOGIN': True,
    'AUTH_HEADER_TYPES': ('Bearer',),
}

# Nombres y flags de las cookies donde viajan los JWT (se setean en la vista
# de login que se crea en el siguiente paso). HttpOnly=True siempre: JS no
# puede leerlas. Secure=True fuera de DEBUG (requiere HTTPS en producción).
AUTH_COOKIE_ACCESS_NAME = 'access_token'
AUTH_COOKIE_REFRESH_NAME = 'refresh_token'
AUTH_COOKIE_HTTPONLY = True
AUTH_COOKIE_SECURE = not DEBUG
AUTH_COOKIE_SAMESITE = 'Lax'


# drf-spectacular (documentación OpenAPI/Swagger de la API)
# https://drf-spectacular.readthedocs.io/

SPECTACULAR_SETTINGS = {
    'TITLE': 'API Tienda Multi-tenant',
    'DESCRIPTION': 'API para la tienda online multi-tenant (Prueba 2 - Desarrollo Backend, INACAP).',
    'VERSION': '1.0.0',
    'SERVE_INCLUDE_SCHEMA': False,
}
